#!/usr/bin/env bash
#
# Distributes skills/payment-foundry/ (the single source of truth for the
# /start-session, /validate-context, and /wrap-up skills) into the locations
# expected by each supported AI coding agent:
#
#   - Claude Code:      .claude/skills/<skill>/SKILL.md
#   - Google Antigravity / AWS Kiro: .agents/skills/payment-foundry/<skill>/SKILL.md
#   - Mistral Vibe:     .vibe/agents/payment-foundry.toml
#
# Re-run this script any time a file under skills/payment-foundry/ changes to
# keep every agent's copy in sync. See setup/other-agents.md for details.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC_DIR="$ROOT_DIR/skills/payment-foundry"

if [ ! -d "$SRC_DIR" ]; then
  echo "error: $SRC_DIR not found" >&2
  exit 1
fi

SKILLS=(start-session validate-context wrap-up)

echo "Distributing skills from skills/payment-foundry/ ..."

# Claude Code
for skill in "${SKILLS[@]}"; do
  mkdir -p "$ROOT_DIR/.claude/skills/$skill"
  cp "$SRC_DIR/$skill/SKILL.md" "$ROOT_DIR/.claude/skills/$skill/SKILL.md"
done
echo "  - Claude Code:       .claude/skills/<skill>/SKILL.md"

# Google Antigravity / AWS Kiro
for skill in "${SKILLS[@]}"; do
  mkdir -p "$ROOT_DIR/.agents/skills/payment-foundry/$skill"
  cp "$SRC_DIR/$skill/SKILL.md" "$ROOT_DIR/.agents/skills/payment-foundry/$skill/SKILL.md"
done
echo "  - Antigravity / Kiro: .agents/skills/payment-foundry/<skill>/SKILL.md"

# Mistral Vibe
mkdir -p "$ROOT_DIR/.vibe/agents"
TOML_FILE="$ROOT_DIR/.vibe/agents/payment-foundry.toml"

extract_field() {
  # extract_field <file> <field>
  grep -m1 "^$2:" "$1" | sed -E "s/^$2:[[:space:]]*//; s/^\"(.*)\"\$/\\1/"
}

{
  echo "# Generated by scripts/setup-agents.sh from skills/payment-foundry/."
  echo "# Re-run that script after editing the skill files, do not edit this file by hand."
  echo
  echo "[agent]"
  echo "name = \"payment-foundry\""
  echo "instructions = \"AGENTS.md\""
  echo "description = \"Engagement Manager for PSP integrations. See AGENTS.md / CLAUDE.md for the full persona and routing rules.\""
  echo
  for skill in "${SKILLS[@]}"; do
    skill_file="$SRC_DIR/$skill/SKILL.md"
    name=$(extract_field "$skill_file" "name")
    description=$(extract_field "$skill_file" "description")
    echo "[[agent.skills]]"
    echo "name = \"$name\""
    echo "description = \"$description\""
    echo "path = \"skills/payment-foundry/$skill/SKILL.md\""
    echo
  done
} > "$TOML_FILE"
echo "  - Mistral Vibe:      .vibe/agents/payment-foundry.toml"

echo "Done."
